# Generated by Django 5.2.1 on 2025-05-24 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=250)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('C', 'Completed'), ('P', 'Pending')], max_length=1)),
            ],
        ),
    ]
